site_name: Interpretador de C - Documentação
theme: 
  name: material
  language: pt-BR
  features:
      - navigation.tabs
      - navigation.tabs.sticky
nav:
  - Home: index.md
  - Sprints:
    - Organização e fluxo de trabalho: docs/sprints/organizacao.md
    - Planejamento: docs/sprints/planejamento.md
    - Sprint 1:
      - Cronograma da sprint: docs/sprints/sprint1/cronograma.md
    - Sprint 2:
      - Cronograma da sprint: docs/sprints/sprint2/cronograma.md
  - O interpretador: 
    - Como rodar o projeto: docs/interpretador/comoRodar.md
    - Glossário de termos: docs/interpretador/glossarioTermos.md